import React from 'react';
import styled from 'styled-components';

const TOS = () => {
  return (
    <Container>
      <Title>TERMS OF SERVICE</Title>
      <SubTitle>Last Modified: April 19, 2024</SubTitle>
      <P>These Terms of Service, including, without limitation, any policies, rules and other terms that are expressly incorporated herein by reference (collectively, the “Terms”), set forth a legally binding agreement between you (“you” or “your”) and Stoned Cold Dreamery LLC, and their respective subsidiaries, parents and affiliates (collectively, “Stoned Cold Dreamery,” “we,” “us,” or “our”). The Terms govern your use of any of our past, present or future (a) websites that link to the Terms, including, without limitation, the website located at www.thestonedcolddreamery.com (collectively, the “Sites ”), (b) content, information, functionality, products or services made available on or through the Sites, and (c) the Mobile Services (as defined below) ((a), (b) and (c) are referred to collectively herein as the “Services”). Please read the Terms carefully before using the Sites or any of the Services.</P>

      <P>ARBITRATION NOTICE: SECTION 27 (DISPUTE RESOLUTION) OF THESE TERMS CONTAINS A MUTUAL ARBITRATION AGREEMENT AND CLASS ACTION WAIVER THAT WAIVES YOUR RIGHT TO A COURT HEARING AND JURY TRIAL. YOU AGREE THAT ANY AND ALL DISPUTES BETWEEN YOU AND US WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION. PLEASE READ SECTION 27 (DISPUTE RESOLUTION) CAREFULLY.</P>

      <SubTitle>1. Acceptance Of Terms</SubTitle>
      <P>By accessing or using the Sites or the Services, or by clicking to accept the Terms when this option is made available to you, you accept and agree to be bound by the Terms (including, without limitation, the Privacy Policy (as defined below)). In addition to the Terms, your access to and use of certain portions or aspects of the Sites and the other Services, or your ability to access and/or use certain Services, may require you to accept additional terms and conditions (collectively, the “Additional Terms”). The Additional Terms are hereby incorporated in and made a part of the Terms by this reference. THESE TERMS GOVERN YOUR ACCESS TO AND USE OF THE SITES AND THE OTHER SERVICES. BY USING THE SITE AND/OR ANY OF THE SERVICES, YOU EXPRESSLY AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO THESE TERMS, DO NOT ACCESS OR USE THE SITES OR THE OTHER SERVICES.</P>

      <SubTitle>2. Age Requirements</SubTitle>
      <P>The Services are intended for a mature audience. None of the Services are directed at children. You must be at least the age of twenty-one (21), and fully able and competent to enter into and abide by the terms and conditions of the Terms, in order to access and use the Services. Individuals under the age of twenty-one (21) are not eligible to use the Sites or the other Services and may not submit any personal information to us. By accessing or using the Services, or by clicking to accept the Terms when this option is made available to you, you represent and warrant that you are at least the age of twenty-one (21), are legally entitled to enter into the Terms, are legally able to enter into any and all purchase agreements with us and our partners, vendors, agents, and service providers, and have the right, authority and capacity to enter into and abide by the terms and conditions of the Terms.</P>

      <SubTitle>3. Modification Of The Terms</SubTitle>
      <P>We may revise the Terms from time to time. We will text you, e-mail you and/or post a notification on the Sites and/or in the Services in the event of any material changes to the Terms. Such changes, whether in the form of modifications, additions, or deletions, shall be effective when specified in the relevant notification or, if the change is not material, immediately upon appearing on the Site regardless of the date of notice. Please check the Terms periodically for changes. Your continued use of the Services following our posting of any changes to the Terms means that you accept and agree to those changes.</P>

      <SubTitle>4. Privacy Policy</SubTitle>
      <P>Our Privacy Policy (the “Privacy Policy”) governs the processing of all personal data collected from you in connection with your use of the Services. All of the terms and conditions of the Privacy Policy are hereby incorporated and made a part of the Terms by this reference. By using the Services, you are agreeing to the Privacy Policy.</P>

      <SubTitle>5. Accessibility</SubTitle>
      <P>We are committed to diversity, inclusion and accessibility. These core values are fundamental to the way we do business and come through in the services we provide and the experiences that we design for people. To this end, we are committed to helping those with disabilities access the Sites and/or the other Services. We strive to provide an excellent online experience for all our guests – including, without limitation, those with sight, hearing, and other disabilities. If you have difficulty using or accessing any element of the Sites or the other Services or if you have any feedback regarding accessibility of the Sites or the other Services, please feel free to contact us at stonedcolddreamery@gmail.com with “Site Accessibility” in the subject line and provide a description of the specific feature you feel is not fully accessible or a suggestion for improvement.</P>

      <SubTitle>6. Account Access Information</SubTitle>
      <P>In the event you are required to create an account to access any part of the Services, you must treat your account information (including, without limitation, your username, password, and any other piece of information required as part of our security procedures) as confidential, and you must not disclose the foregoing to any other person or entity. You also acknowledge that your account is personal to you and agree not to provide any other person or entity with access to the Services or portions of it using your username, password or other security information. You agree to notify us immediately of any unauthorized access to or use of your username or password or any other breach of security. You agree to be responsible for any use of the Services or portions of it using your username, password, or other security information. We have the right to disable any username, password, or other identifier, whether chosen by you or provided by us, at any time, if you have violated any provision of the Terms.</P>

      <SubTitle>7. Mobile Services And Mobile Messaging</SubTitle>
      <P>We may offer certain Services via a mobile device, including, without limitation, (i) the ability to browse from a mobile device, and (ii) SMS based services (collectively, the “Mobile Services”). We may also communicate with you regarding the Services via SMS if you elect to receive such messages (“Mobile Messaging”). To the extent you access the Services through a mobile device or agree to receive Mobile Messaging, your wireless service carrier’s standard charges, data rates and other fees may apply. In addition, downloading, installing, or using certain Services, may be prohibited or restricted by your carrier, and not all Services may work with all carriers or devices. By using the Mobile Services or agreeing to receive Mobile Messaging, you agree that we may communicate with you by SMS, MMS, text message or other electronic means to your mobile device and that certain information about your usage of the Mobile Services may be communicated to us. In the event you change or deactivate your mobile telephone number, you agree to promptly update your account information to ensure that your messages are not sent to the person that acquires your old number. You may opt out of Mobile Messaging at any time by texting STOP in response to a mobile message that you receive from us.</P>

      <SubTitle>8. Restrictions On Use</SubTitle>
      <P>
        We reserve the right to refuse service to anyone for any reason at any time.
        <br />
        You may not use the Services or our products for any illegal or unauthorized purpose nor may you, in the use of the Services, violate any laws in your jurisdiction (including but not limited to copyright laws)
      </P>

      <SubTitle>a. Solely for Personal Use</SubTitle>
      <P>You may use the Services and all associated content solely for your personal use and enjoyment. The Services, or any portion thereof may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without our express written consent.</P>

      <SubTitle>b. Accuracy of Information as Condition to Sites or Services Access</SubTitle>
      <P>To access parts of the Sites or the other Services, you may be asked to provide certain, sometimes personal, information. It is a condition of your use of the Sites or the other Services that all the information you provide on the Sites or the Services is correct, current, and complete.</P>

      <SubTitle>c. Restricted Transmission</SubTitle>
      <P>You agree not to use any device, software, or routine to interfere with the proper functioning of the Sites, the Mobile Services or the other Services. In addition, when accessing or using the Sites or the other Services you may not:</P>

      <Ul>
        <li>Transmit any unlawful, threatening, abusive, libelous, defamatory, obscene, vulgar, pornographic, profane, or indecent information of any kind, including, without limitation, images and language;</li>
        <li>Transmit any message that constitutes, encourages, or incites conduct that would constitute a criminal offense or give rise to civil liability;</li>
        <li>Transmit or solicit any information, software, or other material that violates or infringes upon the rights of others, including, without limitation, material that is an invasion of privacy or publicity rights; is protected by copyright, trademark, or other proprietary rights; or is a derivative work with respect thereto, without first obtaining permission from the owner or right holder;</li>
        <li>Transmit any information, software, or other material that contains a virus, trojan horse, time bomb, worm or other rogue programming or other harmful component;</li>
        <li>Use any software, tool, data, device, or other mechanism to navigate or search the Sites and/or the other Services, other than generally available browsers or a search engine provided by us;</li>
        <li>Use spiders, robots, data mining techniques or other automated devices or programs to catalog, download or otherwise reproduce, store or distribute any information or content available on the Sites or the other Services;</li>
        <li>Frame or utilize framing techniques to enclose any aspect of the Sites or the other Services, including, without limitation, any trademark, logo, or other proprietary information (including, without limitation, , images, text, page layout, or form) without our express written consent; or</li>
        <li>Use any metatags or any other “hidden text” utilizing our name, copyrights or trademarks without our express written consent.</li>
      </Ul>

      <SubTitle>d. Other Restrictions</SubTitle>
      <P>Additionally, you are prohibited from violating or attempting to violate any security features of the Sites, including, without limitation:</P>

      <Ul>
        <li>Accessing content or data not intended for you or logging onto a server that you are not authorized to access;</li>
        <li>Attempting to probe, scan, or test the vulnerability of the Sites, or any associated system or network, or to breach security or authentication measures without proper authorization;</li>
        <li>Interfering or attempting to interfere with service to any visitor, host, or network, including, without limitation, by means of submitting a virus to the Sites or the other Services, overloading, “flooding,” “spamming,” “mail bombing,” or “crashing;”</li>
        <li>Violating security features that prevent or restrict use or copying of any content or enforce limitations on use of the Sites or the other Services or any content on the Sites or the other Services, including, without limitation, by use of any manual or automated software, devices, scripts bots, crawlers, spiders, data miners, scraping or other automatic access tools;</li>
        <li>Using the Sites or the other Services to send unsolicited e-mail, promotions or advertisements for products or services;</li>
        <li>Forging any TCP/IP packet header or any part of the header information in any e-mail or posting; or</li>
        <li>Attempting to modify, reverse-engineer, decompile, disassemble, or otherwise reduce or attempt to reduce to a human-perceivable form any of the source code used by us in providing the Site.</li>
      </Ul>

      <P>Any violation of system or network security may subject you to civil and/or criminal liability. A breach or violation of any of the Terms may result in an immediate termination of your Services.</P>

      <SubTitle>9. User Convenants</SubTitle>
      <P>By accessing or using the Services, you agree to, acknowledge, and represent as follows:</P>

      <Ul>
        <li>You will comply with all applicable federal, state or local laws in using the Services, and you will not perform or fail to perform any act that you know or reasonably should know would place us or our affiliates in violation of any applicable law.</li>
        <li>You have the authority and capacity, under the laws of the state or jurisdiction in which you reside, to make the representations and warranties and be bound by the covenants provided herein.</li>
      </Ul>

      <SubTitle>10. Copyrights, Trademarks, And Other Proprietary Rights</SubTitle>
      <P>When accessing and using the Services, you agree to obey the law and to respect the intellectual property rights of others. As between you and us, all content on the Site and the other Services, including, without limitation, text, logos, hidden text within our source code, trademarks, software, photos, video, images, graphics, music, audio-visual content, podcasts, recordings, sound, emails, texts, push notices or any other digital media, is owned by us and/or our licensors and is subject to protection by patent, copyright, trademark, or other proprietary rights. In addition, the entire content of the Sites and the other Services is copyrighted as a collective work under the United States and international copyright laws, and we own the copyright in the selection, coordination, arrangement, and enhancement of such content.</P>

      <P>All trademarks, trade names, trade dress, logos, and service marks (collectively, the “Trademarks”) appearing on the Site and/or the other Services are the property of their respective owners, including, without limitation, in some instances, us and/or other third parties with whom we work. Nothing contained on the Sites or the other Services, the other Services or the Terms serves to grant you, by implication or otherwise, a license or right to use any of the Trademarks or copyrights owned by us or by any third party.</P>

      <P>Except as expressly provided herein, you may not use, modify, create derivative works of, copy, redistribute, reproduce, publish, transmit, display, commercialize, or in any other way exploit any content or material from the Sites or the other Services without express written permission from us and, if applicable, the respective copyright owner. You acknowledge and agree that you do not acquire any ownership rights by accessing or using the Services.</P>

      <SubTitle>11. User Comments, Feedback And Other Submissions</SubTitle>
      <P>If, at our request, you send certain specific submissions (for example contest entries or product reviews) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, "Submissions"), you hereby grant to us and our affiliates, the royalty-free, perpetual, irrevocable, worldwide, transferable, non-exclusive right and license to use, reproduce, modify, adapt, publish, share, re-post, translate, create derivative works of, and display in any medium, your Submissions. Any such content you provide to us shall be deemed to be non-confidential and nonproprietary and we shall be free to use such information on an unrestricted basis. We are and shall be under no obligation (1) to maintain any Submissions in confidence; (2) to pay compensation for any Submissions; or (3) to respond to any Submissions. We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or the Terms. You agree that your Submissions will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that your Submissions will not contain libelous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Services. You may not use a false e-mail address, pretend to be someone other than yourself, or otherwise mislead us or third parties as to the origin of any Submissions. You are solely responsible for any Submissions you make and their accuracy or appropriateness. We take no responsibility and assume no liability for any Submissions posted by you or any third-party.</P>

      <SubTitle>12. Electronic Communications</SubTitle>
      <P>When you use the Services, or send e-mails, text messages, and other communications from your desktop or mobile device to us, you may be communicating with us electronically. You consent to receive communications from us electronically, such as e-mails, texts, mobile push notices, or notices and messages on the Services, and you can retain copies of these communications for your records. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</P>

      <SubTitle>13. Monitoring; Copyright Complaints</SubTitle>
      <P>You agree that we have the right, but not the obligation, to monitor, suspend, terminate, edit, disclose, refuse to post, or remove at any time, for any reason in our sole discretion, any material, content, and/or activity anywhere on the Sites or the other Services, including, without limitation, any content you might post, which posting shall only be done if and to the extent permitted by the Terms, invited on the Sites or the other Services and for which you have adequate rights to post. In the event you post or provide content in violation of the Terms or to which you do not have adequate rights, we may suspend or terminate your access to or use of the Site. Notwithstanding this right, we do not and cannot review all materials submitted to the Site. If notified, we will investigate an allegation that content transmitted to us is in violation of the Terms and determine whether to have the communication removed. However, we assume no responsibility or liability arising from or relating to any actions or content transmitted by or between you or any third party within or outside of the Sites or the other Services, including, without limitation, , any error, defamation, libel, slander, omission, falsehood, obscenity, pornography, profanity, danger, or inaccuracy contained therein.</P>

      <SubTitle>Digital Millennium Copyright Act</SubTitle>
      <P>We may, in appropriate circumstances, terminate the access of users who infringe or otherwise violate the rights of others. While we reserve the right to terminate the access of users who infringe or otherwise violate the rights of others in our sole discretion, if you are a Repeat Offender (as defined below), your access to the Sites or the other Services will be suspended or terminated. “Repeat Offender” shall mean any user of the Sites or the other Services against whom we receive three (3) or more Infringement Notifications (as defined below).</P>

      <P>If you believe that your work has been copied and is accessible on the Sites or the other Services in a way that constitutes copyright infringement, you may notify us (each, an “Infringement Notification”) by providing the following information (as required by the Online Copyright Infringement Liability Limitation Act of the Digital Millennium Copyright Act (“DMCA”), 17 U.S.C. sec. 512):</P>
      <Ul>
        <li>A physical or electronic signature of the person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>
        <li>Identification of the copyrighted work claimed to have been infringed, or if multiple copyrighted works at the Sites or the other Services are covered by a single notification, a representative list of such works at the Site;</li>
        <li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material;</li>
        <li>Information reasonably sufficient to permit us to contact you, such as an address, telephone number, and if available, an e-mail address;</li>
        <li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by you, your agent, or the law; and</li>
        <li>A statement that the information in the notification is accurate, and, under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
      </Ul>

      <P>Please send the written communication to our copyright agent by e-mail and by U.S. Mail to:</P>

      <P>Stoned Cold Dreamery LLC 555 Vesey Street New York, NY 10080-0001 Attention: DMCA Agent</P>

      <P>-OR-</P>

      <P>E-mail: stonedcolddreamery@gmail.com</P>

      <P>E-mail Subject: “DMCA Request”</P>

      <P>14. Third-party Sites; Social Media</P>

      <P>Our home goods store is hosted on Shopify and other aspects of the Services are hosted by other third parties. They provide us with online e-commerce platforms that allows products and services to be sold to you. We may provide links and pointers to websites, goods, and/or services maintained, owned, or controlled by others (collectively, “Third-Party Sites”) that are not affiliated with us and may be located in different countries and that may subject to different regulatory and other legal requirements. We have not reviewed all of the Third-Party Sites linked to the Sites or the other Services and are not responsible for the content or services offered on such Third-Party Sites, including, without limitation, any advertising, order processing and fulfillment, or payment terms related to such Third-Party Sites. Access to Third-Party Sites through the Sites or the other Services does not constitute an endorsement by us or any of our subsidiaries or affiliates of any such Third-Party Sites, or the content or services offered by them. We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party’s policies and practices and make sure you understand them before you engage in any transaction. We have no responsibility or liability for these Third-Party Sites’ independent policies or actions and are not responsible for the privacy practices of such Third-Party Sites or retailers. Complaints, claims, concerns, or questions regarding Third-Party Sites should be directed to the applicable third party. If we provide links to social media platforms, such as Instagram or Twitter, and you choose to visit such social media platforms through our links, please note that the personal information you post, transmit, or otherwise make available on or through such social media platforms may be viewed by the general public. We do not control any content or information made available on such social media platforms and we are not responsible for any third-party use of any such content or information, including, without limitation, personally identifiable information, that you have posted, transmitted, or otherwise made available on such social media platforms.</P>

      <SubTitle>15. Unavailability Of Service; Updates; Information; Errors And Omission</SubTitle>
      <P>We will not be liable if, for any reason, all or part of the Sites or the other Services is ever unavailable. We reserve the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Sites or the other Services, or any part thereof, with or without notice. We undertake no obligation to update, amend, or clarify information on the Sites or the other Services, except as required by law. No specified update or refresh date applied on the Sites should be taken to indicate that all information on the Sites or the other Services has been modified or updated. Please remember when reviewing information on the Sites or the other Services that such information may not represent the complete information available on a subject. In addition, subsequent events or changes in circumstances may cause existing information on the Sites or the other Services to become inaccurate or incomplete.</P>
      <P>We do not warrant the accuracy, completeness or currency of any information on the Site and/or the other Services and do not guarantee or accept any responsibility or liability therefor.</P>

      <SubTitle>16. Product Descriptions</SubTitle>
      <P>We attempt to be accurate in our product descriptions, however we do not represent or warrant that product descriptions or other content on any of the Services is accurate, complete, reliable, current, or error-free. We have made every effort to display as accurately as possible the colors and images of our products. We cannot guarantee that the images on the Services or your computer monitor’s display of any color will be accurate. If a product offered by us directly is not as described, your sole remedy with respect thereto is to return it in unused condition.</P>

      <SubTitle>17. Sanctions And Export Policy</SubTitle>
      <P>You may not use any Service if you are the subject of U.S. sanctions or of sanctions consistent with U.S. law imposed by the governments of the country where you are using the Services. You must comply with all U.S. or other export and re-export restrictions that may apply to goods, software (including Stoned Cold Dreamery Software), technology, and services.</P>

      <SubTitle>18. Limited Availability Of Products Or Services</SubTitle>
      <P>Certain products or services may be available exclusively online through the website. These products or services may have limited quantities and are subject to return or exchange only according to our return policy. We reserve the right, but are not obligated, to limit the sales of our products or Services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any products or services that we offer. All descriptions of products or product pricing are subject to change at any time without notice, at the sole discretion of us. We reserve the right to discontinue any product at any time. Any offer for any product or service made on this site is void where prohibited.</P>

      <SubTitle>19. Purchases</SubTitle>
      <SubTitle>Products, Prices, and Promotions</SubTitle>
      <P>Products offered on the Sites or the other Services are offered subject to availability. All products should be used strictly in accordance with any applicable instructions, precautions and guidelines. All prices, discounts, and promotions posted on the Sites or the other Services are subject to change without notice. We may, from time to time, offer promotions or other discounts on product purchases. We reserve the right to suspend any such promotions, update product information and change prices at any time without notice. Furthermore, we reserve the right to change, limit, refuse, or cancel any order you place with us at our sole discretion. If we change or cancel an order, we will attempt to notify you by contacting the e-mail and/or billing address and/or phone number provided at the time the order was made. We strive to display accurate price information; however, we may, on occasion, make inadvertent typographical errors, inaccuracies, or omissions related to pricing and availability. We reserve the right to correct any errors, inaccuracies, or omissions at any time, and to cancel any orders arising from such occurrences.</P>
      
      <SubTitle>Coupons/Discount Codes</SubTitle>
      <P>Use is limited to one (1) time per coupon and/or discount code per customer and subject to the terms and conditions of the applicable coupon and/or discount code. Discounts will be applied at checkout. Online offers have no cash value and are not redeemable for cash. Coupons and discount codes are not valid on previous purchases or when combined with other promotional offers.</P>

      <SubTitle>Payment Terms</SubTitle>
      <P>Terms of payment are within our sole discretion and, unless otherwise agreed by us in writing, payment must be received by us before our acceptance of an order. By entering into any transaction on the Sites or the other Services, you represent, warrant and covenant that all information you provide is true, correct, and complete (including without limitation, your credit card information and billing address); that any credit card transactions submitted by you are authorized; that charges incurred by you will be honored by your credit card company; that you will pay charges incurred by you at the posted prices, including, without limitation, shipping and handling charges and all applicable taxes, if any, regardless of the amount quoted on the Sites or the other Services at the time of your order; and that you are the legal holder of any credit card or payment account used to enter into any transaction on the Site.</P>
      <P>If, in our sole discretion, we determine that: (i) your means of payment is not valid, (ii) a transaction is not authorized, (iii) your means of payment cannot be processed or verified at the time of any charge, (iv) a charge is disputed for any reason other than failure by us to deliver the item(s) purchased by you, (v) you have abused or misused promotions or promotion codes, as applicable, or (vi) you have otherwise used the Sites or the other Services to enter into an improper transaction, we reserve the right to immediately terminate any pending transactions, suspend your access to the Sites or the other Services, and terminate all of our obligations hereunder.</P>

      <SubTitle>Payment Processing</SubTitle>
      <P>By agreeing to the Terms, you consent that the payment processing services for products purchased on the Sites are provided by Stripe.</P>

      <SubTitle>Shipments; Delivery</SubTitle>
      <P>We will arrange for shipment of the products to you. Risk of loss passes to you upon delivery of the products to the carrier. You will pay all shipping and handling charges specified during the ordering process. Shipping and delivery dates are estimates only and cannot be guaranteed. We are not liable for any delays in shipments. We will provide customers with tracking information including expected shipping dates, but we will not be held responsible for any delays, damages or losses due to (but not limited to) natural disasters, acts of federal, state or local government, fires, floods, strikes, lockouts, freight embargoes, and acts of God. Customers can pursue claims for lost and damaged packages through the shipping courier.</P>

      <SubTitle>Returns and Refunds</SubTitle>
      <P>Except for any products designated on the Sites or the other Services as Final Sale (non-cancellable, non-returnable, non-exchangeable) our policy is to accept returns of products within thirty (30) days following delivery of products and refund your purchase price, less the original shipping and handling costs and less the shipping and handling costs for such return, so long as such return is made with valid proof of purchase and provided such products are returned in unused and unopened condition. To return products, you must first email us at stonedcolddreamery@gamil.com to initiate the return. You are responsible for all shipping and handling charges on returned items unless otherwise specified.</P>
      <P>If you feel that you did not receive your purchased product and you have been charged, please email us at stonedcolddreamery@gmail.com.</P>

      <SubTitle>Resale of Products</SubTitle>
      <P>The Sites or the other Services sells products to retail consumers only. You shall not use the Sites or the other Services to purchase products for re-sale or export. We reserve the right to immediately bar access to the Sites or the other Services and terminate the account of any user who violates this provision.</P>

      <SubTitle>Accuracy of Billing and Account Information</SubTitle>
      <P>We reserve the right to refuse any order you place with us. We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. These restrictions may include orders placed by or under the same customer account, the same credit card, and/or orders that use the same billing and/or shipping address. In the event that we make a change to or cancel an order, we may attempt to notify you by contacting the e-mail and/or billing address/phone number provided at the time the order was made. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers or distributors.</P>
      <P>You agree to provide current, complete and accurate purchase and account information for all purchases made at our store. You agree to promptly update your account and other information, including your email address and credit card numbers and expiration dates, so that we can complete your transactions and contact you as needed.</P>

      <SubTitle>Creating an Account</SubTitle>
      <P>In order to access certain content, material, products or services, or place an order on the Sites or the other Services, you may be asked to create an account. As part of the registration process, you may be asked to click to agree to the Terms (including, without limitation, the Privacy Policy), and may then be asked to select or submit a username and password. You may also be required to provide us with certain information about yourself including some types of personally identifiable information, including your legal name, phone number, address, email address, gender, and age. You are responsible for ensuring that your password and account login are kept secret, safe, and secure at all times. We will not be held responsible or liable for any misuse of your account in the event that a third party has access to and uses your password and account login in any way.</P>

      <SubTitle>Validating Your Order</SubTitle>
      <P>After you place an order using our shopping cart, we will check the information you give us for validity, by verifying your method of payment or shipping address. We reserve the right to reject any order you place with us, and/or to limit quantities on any order, without giving any reason. If we reject your order, we will attempt to notify you using the e-mail address you have given us with the order. Your credit or debit card will normally not be charged if we reject an order, but we will process a refund if the charge has been made against your card.</P>

      <SubTitle>Order Acceptance/Confirmation</SubTitle>
      <P>We reserve the right to refuse service, including but not limited to, order fulfillment, customer support, and technical support, to anyone for any reason. An invoice does not represent an actual acceptance of an order nor does it represent an offer to sell, rather, we reserve the right to decline an order for any reason, even after an order invoice is issued.</P>

      <SubTitle>Taxes</SubTitle>
      <P>You are responsible for any sales, duty or other governmental taxes or fees due with respect to your order. We will collect applicable sales tax if we determine that we have a duty to collect sales tax. We will present any taxes that we are required to collect at checkout, but note that actual taxes charged may be adjusted from the amount shown at checkout. Several factors may cause this, such as variances between processor programs and changes in tax rates.</P>

      <SubTitle>Order Limitations/Limited Quantities</SubTitle>
      <P>We may, at our own discretion, limit or cancel quantities purchased per person, per household or per order. We also reserve the right to reject any order you place with us. In the event we make a change to an order, we will attempt to notify you by contacting the e-mail and/or billing address provided at the time the order was made.</P>

      <SubTitle>Collections</SubTitle>
      <P>In the event we must pursue collections of any debt owed to the company resulting from a sales transaction, not limited to fraud, credit card reversals, credit accounts, etc., we will be entitled to actual costs associated with the collections, including, but not limited to, actual legal fees and costs, travel fees, airfare, mileage, lodging, and other necessary costs associated with the collections.</P>

      <SubTitle>Product Updates/Errors on Site</SubTitle>
      <P>Product information and prices displayed on the Sites and the other Services are subject to change without notice. Errors will be corrected where discovered, and we reserve the right to revoke any stated offer and to correct any errors, inaccuracies or omissions including after an order has been submitted and whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is cancelled, we will issue a credit to your credit card account in the amount of the charge. Individual bank policies will dictate when this amount is credited to your account. If you are not fully satisfied with your purchase, you may return it in accordance with our return policy.</P>

      <SubTitle>Questions</SubTitle>
      <P>If you have any questions or concerns with your order, please e-mail us at stonedcolddreamery@gmail.com.</P>

      <SubTitle>20. Cannabis</SubTitle>
      <P>Not everyone accepts cannabis use as permissible. For example, some employers may have anti-drug policies that disallow cannabis use.</P>
      <P>You acknowledge that by interacting with the Services, providing your information to us, allowing us to collect data about you, permitting us to send you communications, or using our products, could imply to employers, friends, family, or others that you are a cannabis product user, which could have unwanted social, legal, employment, economic, or other impacts that could affect you, including, without limitation, your loss of employment, and that Houseplant shall not be held liable for damages arising out of or connected with the foregoing because your use of the Services and our products is solely at your own risk.</P>
      <P>The Services support our licensing of intellectual property to various licensed cannabis facilities in various states in which such uses are permitted by local and state law. All cannabis products advertised on the Site are offered by the licensee thereof solely in locations where and under conditions in which such products may be legally sold.</P>
      <P>Cannabis is a Schedule 1 Controlled Substance under the Controlled Substance Act (21 U.S.C. 802) and therefore the cultivation, distribution, and possession of cannabis, or conspiring with or assisting others to do the same, is a crime under federal law and can result in significant criminal and civil penalties. You further acknowledge that medical use is not recognized as a valid defense under federal laws regulating cannabis, and that the interstate transportation of cannabis is a federal offense. ENGAGING IN ACTIVITIES OR BUSINESS RELATED TO CANNABIS IS AT YOUR OWN RISK.</P>
      <P>Keep all cannabis and cannabis products out of reach of children and animals. Use of cannabis while pregnant or breastfeeding may be harmful. If you are pregnant or may be pregnant, breastfeeding, suffering from a known health condition, or taking any prescription medications, you should consult a physician or other health care professional prior to using cannabis. Intoxicating effects of cannabis and cannabis products may be delayed up to two (2) hours. Consumption of cannabis and cannabis products impairs your ability to drive and operate machinery. Do not operate vehicles or machinery while under the influence of cannabis.</P>
      <P>Not everyone accepts cannabis use as permissible. For example, some employers may have anti-drug policies that disallow cannabis use.</P>
      <P>You assume the risk of any-and-all damage or loss incurred as a result of your consumption of cannabis or cannabis products. Although the Services and licensees may provide information regarding cannabis and cannabis products, including, without limitation, potency, pharmacologically active ingredients, source of cultivation, recommended uses and benefits, and all other descriptions or information (collectively, “Cannabis Information”), such Cannabis Information should in no way be construed as medical advice nor is it intended to cover all possible uses, directions, precautions, or adverse effects. All Cannabis Information is provided for informational and educational purposes only and is not intended to be a substitute for medical advice under any circumstance. Always consult your primary care physician or other qualified healthcare provider prior to using cannabis or a cannabis product for treatment of a medical condition. Never disregard professional medical advice or fail to seek it following receipt of Cannabis Information from the Services or a licensee where your use of cannabis is to treat a medical condition. We cannot guarantee the accuracy of any Cannabis Information and you should not rely on such Cannabis Information.</P>

      <SubTitle>21. Disclaimer of Warranties</SubTitle>
      <P>The site and the other services (including, without limitation, the mobile services) may provide you with certain information, including, without limitation, personalized activity suggestions, personalized product recommendations, cannabis related information, and information regarding different strains of medical cannabis and their potential suitability for treating different diagnoses. All such information is provided for general information purposes only and does not constitute legal, medical, or other professional advice or an opinion of any kind. The services (including, without limitation, the mobile services) do not replace any medical professional or medical resource and does not provide medical or other licensed professional advice. Further, all such information is provided on an “as is” and “as available” basis and you hereby expressly acknowledge and agree that any use of, or reliance on, such information is at your sole risk. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of information you have obtained through the site or the services. If you think you may have a medical emergency, call your doctor or 911 immediately.</P>
      <P>Further, you expressly acknowledge and agree that your use of the site and the services is at your sole risk. The site and the services are provided on an “as is” and “as available” basis. We expressly disclaim all warranties of any kind, whether express or implied, including, without limitation, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We make no warranty that the site or the services will meet your requirements or will be uninterrupted, timely, unfailingly secure, or error-free, that the results that may be obtained from the use of the site or the services will be accurate or reliable, that the quality of any information or materials obtained by you through the site or the services will meet your expectations, and that any errors in the site or the services will be corrected. Your sole remedy against us for dissatisfaction with the site or the services is to stop using the site or the services, as applicable. The foregoing limitation of relief is an essential part of the bargain between you and us under these terms of use. Please note that some jurisdictions do not allow limitations on the length or scope of an implied warranty, so the above limitations may not apply to you.</P>

      <SubTitle>22. Limitation of Liability</SubTitle>
      <P>To the fullest extent permitted under applicable law, in no event shall we and/or our successors, assigns, affiliates, licensors, service providers, content providers, members, employees, agents, officers, directors, and managers be liable for any incidental, direct, indirect, punitive, actual, consequential, special, exemplary, or other damages, including, but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if we have been advised of the possibility of such damages or such damages are reasonable foreseeable), resulting from (I) the use or the inability to use the site or the services; (ii) any act or omission by you that is based (in whole or in part) on any information, statement or content that is provided or otherwise made available to you by or through the site or the services; (iii) unauthorized access to or alteration of your transmissions or other data; or (iv) statements or conduct of any third party on the site or the mobile services. In no event shall the collective liability of houseplant and its successors, assigns, affiliates, licensors, service providers, content providers, members, employees, agents, officers, directors, and managers to you, for any and all damages, losses, and causes of action, whether in contract, tort or otherwise, exceed, in the aggregate, one hundred U.S. Dollars ($100). Some jurisdictions do not allow the exclusion of certain warranties and/or the limitation of liability for incidental or consequential damages. Accordingly, in certain jurisdictions, some of the above limitations of liability may not apply to you; all other provisions of the terms remain in full force and effect.</P>

      <SubTitle>23. Indemnification</SubTitle>
      <P>You agree to indemnify, defend, and hold harmless us, our affiliates, our subsidiaries, and each of our and their respective shareholders, members, managers, directors, officers, employees, personnel, agents, successors and assigns from and against any and all claims, allegations, demands, actions, causes of action, lawsuits, investigations and proceedings (including, without limitation, any and all liability, damages, costs, expenses (including, without limitation, reasonable attorneys’ fees), settlements, fines, penalties and losses of any kind or nature whatsoever resulting from any of the foregoing) arising out of or in connection with: (i) your violation or breach of the Terms; (ii) your use of the Services; (iii) your dispute with another user; (iv) your violation of any rights of any third party; or (v) your violation of applicable law. This indemnification obligation will continue after you stop using the Services. We reserve the right to assume the exclusive defense and control of any claim and matter otherwise subject to indemnification by you at your expense, and you shall not in any event settle or otherwise dispose of any matter without our prior written consent.</P>

      <SubTitle>24. Force Majeure</SubTitle>
      <P>We will not be liable or responsible to you, nor be deemed to have defaulted or breached the Terms, for any failure or delay in our performance under the Terms when and to the extent such failure or delay is caused by or results from acts or circumstances beyond our reasonable control, including, without limitation, acts of God, flood, fire, earthquake, explosion, governmental actions, war, invasion or hostilities (whether war is declared or not), terrorist threats or acts, riot or other civil unrest, national emergency, revolution, insurrection, epidemic, pandemic, lockouts, strikes or other labor disputes (whether or not relating to our workforce), restraints or delays affecting carriers, inability to obtain or delay in obtaining adequate or suitable supplies, breakdown of materials or telecommunications, or power outage.</P>

      <SubTitle>25. Notices</SubTitle>
      <P>We may send you responses or notices by text message, e-mail, posting to the Sites or the other Services, or written communication sent by U.S. Postal Service. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</P>

      <SubTitle>26. Governing Law</SubTitle>
      <P>These Terms and your use of the Services shall be governed by and construed for both substantive and procedural purposes in accordance with the laws of the State of New York, U.S.A., without giving effect to any principles of any choice or conflict of law provision or rule (whether of the State of New York or any other jurisdiction) that would cause the laws of any jurisdiction other than those of the State of New York to apply.</P>

      <SubTitle>27. Dispute Resolution</SubTitle>
      <SubTitle>Timing of Claims</SubTitle>
      <P>Any cause of action or claim you may have with respect to the Services or any product or service acquired thereunder must be commenced within one (1) year after the claim or cause of action arises.</P>

      <SubTitle>Arbitration and Venue</SubTitle>
      <P>Any dispute relating in any way to your use of the Services shall be submitted to confidential arbitration in Los Angeles, New York, except that, to the extent you have in any manner violated or threatened to violate our intellectual property rights, we may seek injunctive or other appropriate relief in any state or federal court, and you consent to jurisdiction and venue in such courts. Arbitration under the Terms shall be conducted under the rules then prevailing of the American Arbitration Association in accordance with its Commercial Arbitration Rules and before a single arbitrator.</P>
      <P>Ultimately, the selected arbitrator must have expertise in the subject matter of the dispute. The expenses of the arbitration charged by the arbitrator shall be borne by the non-prevailing party or otherwise as appropriately allocated between the parties to the arbitration by the arbitrator in his or her discretion. However, in every other regard, each party shall pay for and bear its own costs and legal fees, costs, and expenses. The arbitration shall be completed within one hundred twenty (120) days of either giving notice or filing a demand to arbitrate with the American Arbitration Association (whichever shall first occur).</P>


      <SubTitle>Final Arbitration</SubTitle>
      <P>The arbitrator’s award shall be binding and may be entered as a judgment in any court of competent jurisdiction. The testimony, evidence, ruling, and all documentation regarding any arbitration shall be considered confidential information. Neither party may use, disclose, or divulge any such information unless otherwise required by law.</P>

      <SubTitle>Class Action Waiver</SubTitle>
      <P>To the fullest extent permitted by applicable law, no arbitration under the Terms shall be joined to an arbitration involving any other party subject to the Terms, whether through class arbitration proceedings or otherwise. You agree to an arbitration on an individual basis. In any dispute, NEITHER YOU NOR WE WILL BE ENTITLED TO JOIN OR CONSOLIDATE CLAIMS BY OR AGAINST OTHER USERS IN COURT OR IN ARBITRATION OR OTHERWISE PARTICIPATE IN ANY CLAIM AS A CLASS REPRESENTATIVE, CLASS MEMBER, OR IN A PRIVATE ATTORNEY GENERAL CAPACITY. The arbitral tribunal may not consolidate more than one (1) person’s claims and may not otherwise preside over any form of a representative or class proceeding. The arbitral tribunal has no power to consider the enforceability of this class arbitration waiver and any challenge to the class arbitration waiver may only be raised in a court of competent jurisdiction.</P>

      <SubTitle>28. Miscellaneous</SubTitle>
      <P>The division of the Terms into sections and the headings of the various sections in the Terms are for convenience of reference only and shall not affect the construction or interpretation of the Terms. You acknowledge and agree that any principle of construction or rule of law that provides that an agreement shall be construed against the drafter of the agreement in the event of any inconsistency or ambiguity in such agreement shall not apply to the Terms. Our failure to insist upon or enforce strict performance of any provision of the Terms shall not be construed as a waiver of any provision or right. Neither the course of conduct between the parties nor trade practice shall act to modify any of the Terms. We may assign our rights and duties under the Terms to any party at any time without notice to you and without your express consent. You will not assign any of your rights or delegate any of your obligations under the Terms without our prior written consent. Any purported assignment or delegation in violation of this Section is null and void. No assignment or delegation relieves you of any of your obligations under the Terms. There shall be no third-party beneficiaries to the Terms. Any provision of the Terms that contemplates performance or observance subsequent to any expiration or termination of the Terms, or which is otherwise necessary to interpret the respective rights and obligations of the parties hereunder, shall survive any expiration or termination of the Terms and continue in full force and effect. If any provision of the Terms shall be held unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from the Terms and shall not affect the validity and enforceability of any remaining provisions. These Terms, together with the Privacy Policy, and all other documents incorporated herein by reference, constitute the entire agreement between the parties pertaining to the subject matter hereof and supersede any agreements previously existing between the parties with respect to such subject matter.</P>

      <SubTitle>29. Notice For New York Users</SubTitle>
      <P>Under New York Civil Code Section 1789.3, New York users of the Sites and the other Services are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the New York Department of Consumer Affairs may be contacted in writing at 1625 North Market Blvd., Suite N. 112, Sacramento, CA 95834, or by telephone at (916) 445-1254 or (800) 952-5210. We may be contacted via e-mail at stonedcolddreamery@gmail.com.</P>

      <SubTitle>30. Acknowledgement Of Legal Restrictions</SubTitle>
      <P>Information provided on the Sites or the other Services is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Persons who choose to access the Sites or the other Services from such locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.</P>

      <SubTitle>31. Houseplant Digital Gift Cards</SubTitle>
      <P>Your use of this card (“Gift Card”) constitutes acceptance of these terms and conditions, and you agree that you will comply with all Gift Card terms. Key terms are as follows:</P>
      <P>CARD DOES NOT EXPIRE AND THERE ARE NO FEES ASSOCIATED WITH USE OF THIS CARD, unless otherwise specified in connection with certain promotional or charitable Cards. Houseplant E-Gift Cards (“Gift Cards” or “Cards”) are issued and managed by S49 Ventures, LLC (“Houseplant”, “we”, “our”) and can be applied in full or in part only to purchases of Houseplant products and services found at www.houselant.com. Cards purchased in the United States may be redeemed for online purchases only in the United States, its territories, and possessions; Gift Cards may not be purchased, redeemed, or used outside the United States. Cards are nonrefundable and are not redeemable for cash (except as required by law), and merchandise purchased with gift cards cannot be returned for a cash refund, exchanged, or resold. Cards cannot be used for previous purchases, merchandise credits, or the purchase of gift cards or fundraising items. No credit card, credit line, overdraft protection, or deposit account is associated with your Gift Card. Gift Card balances cannot be assigned transferred. IF LOST OR STOLEN, THIS CARD CANNOT BE REPLACED.</P>
      <P>Gift Card(s) must be presented at the time of purchase and available balance will be applied to your purchase. If Gift Card holder's purchase exceeds the amount of that Gift Card's balance, the Gift Card holder must pay the difference by another means.</P>
      <P>Houseplant is not responsible for lost or stolen Cards. Risk of loss and title for Cards passes to the purchaser upon transfer or electronic transmission to the recipient; for avoidance of doubt, such recipient may not always be you. Gift Card is void if copied, altered, transferred, purchased or sold. We reserve the right to limit quantities of Gift Cards purchased by any person or entity and to cancel a Gift Card if we believe that the Gift Card was obtained through fraudulent or unauthorized means. Houseplant reserves the right to close accounts and/or request alternative forms of payment if a Card is fraudulently obtained or used.</P>
      <P>Purchases of Gift Cards are final and not refundable. We reserve the right to correct the balance of a Gift Card if we believe that a billing error has occurred, and we disclaim all liability for any such billing errors.</P>
      <P>Purchase, redemption, and use of Cards are subject to our Website Terms of Use, Privacy Policy, and other terms or policies in effect at the time, as applicable, and use of the Gift Card constitutes acceptance thereof. For information about how we collect, use and disclose information relating to use of our Website, please see our Privacy Policy at [https://houseplant.com/privacy-policy]. We, may disclose to the purchaser of a Card whether or not the recipient has redeemed the Card. Applicable terms and conditions are subject to change without notice. If the laws pertaining to this Gift Card require additional or different terms or conditions, then such terms and conditions shall apply. Use of a gift card is governed by the laws of the State of New York. From time to time, we may offer limited availability promotional gift cards, credits, or codes that have different terms and conditions; please review those terms and conditions, carefully as they may expire or have restrictions that are different.</P>
      <P>S49 VENTURES, LLC, AND ITS LICENSEES, AFFILIATES, LICENSORS, AGENTS AND REPRESENTATIVES, MAKE NO WARRANTIES, EXPRESS OR IMPLIED, WITH RESPECT TO CARDS, CREDITS, OR CODES, AND/OR THE WWW.HOUSEPLANT.COM WEBSITE, INCLUDING, WITHOUT LIMITATION, ANY EXPRESS OR IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. IN THE EVENT THAT A CARD, CREDIT OR CODE IS NONFUNCTIONAL, YOUR SOLE REMEDY, AND OUR SOLE LIABILITY, SHALL BE THE REPLACEMENT OF SUCH CARD, CREDIT OR CODE. THESE LIMITATIONS MAY NOT APPLY TO YOU. CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY ALSO HAVE ADDITIONAL RIGHTS.</P>
      <P>If you have any questions regarding these Terms or your Cards, or to make a balance inquiry about your Gift Card, email stonedcolddreamery@gmail.com or login at www.houseplant.com.</P>

      <SubTitle>32. Questions</SubTitle>
      <P>If you have any questions or comments regarding the Terms, the Privacy Policy, the Sites or the other Services, please feel free to contact us at stonedcolddreamery@gmail.com.</P>

    </Container>
  );
};

const Container = styled.div`
  margin-top: 10vh;
  padding: 40px;
  color: #104e65;
`;
const Title = styled.h1`
  text-align: center;
  font-family: Bebas Neue;
  font-size: 15vw;
`;
const UnderlineTitle = styled.h3`
  text-decoration: underline;
`;
const SubTitle = styled.h3``;
const P = styled.p`
  line-height: 2.5vw;
  font-size: 1.5vw;
`;
const Ul = styled.ul`
  line-height: 2.5vw;
`;


export default TOS;
