export const indica_jar = require('/Users/jonathannarine/GithubRepos/cold_stoned_dreamery/src/photo_assets/signature_flower/indica_jar.jpg')
export const hybrid_jar = require('/Users/jonathannarine/GithubRepos/cold_stoned_dreamery/src/photo_assets/signature_flower/hybrid_jar.jpg')
export const sativa_jar = require('/Users/jonathannarine/GithubRepos/cold_stoned_dreamery/src/photo_assets/signature_flower/sativa_jar.jpg')
export const all_packs = require('/Users/jonathannarine/GithubRepos/cold_stoned_dreamery/src/photo_assets/signature_flower/all_packs.jpg')
export const reserve = require('/Users/jonathannarine/GithubRepos/cold_stoned_dreamery/src/photo_assets/signature_flower/reserve.jpg')
export const joint_box_packaging = require('/Users/jonathannarine/GithubRepos/cold_stoned_dreamery/src/photo_assets/signature_flower/joint_box_packaging.jpg')
export const vape_box = require('/Users/jonathannarine/GithubRepos/cold_stoned_dreamery/src/photo_assets/signature_flower/vape_box.jpg')